FROM python:3.6
WORKDIR /code
COPY ./pity/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./pity /code/pity
CMD ["uvicorn", "main:pity", "--proxy-headers", "--host", "0.0.0.0", "--port", "80"]